<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_dosen extends CI_Model
{

    public $table = 'tb_dosen';
    public $id = 'id_dosen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_dosen', $q);
	$this->db->or_like('id_prodi', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_dosen', $q);
	$this->db->or_like('gelar_depan', $q);
	$this->db->or_like('gelar_belakang', $q);
	$this->db->or_like('jabatan_akademik', $q);
	$this->db->or_like('golongan_kepangkatan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('ikatan_kerja', $q);
	$this->db->or_like('status_aktif', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('bidang_ilmu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dosen', $q);
	$this->db->or_like('id_prodi', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_dosen', $q);
	$this->db->or_like('gelar_depan', $q);
	$this->db->or_like('gelar_belakang', $q);
	$this->db->or_like('jabatan_akademik', $q);
	$this->db->or_like('golongan_kepangkatan', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('ikatan_kerja', $q);
	$this->db->or_like('status_aktif', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('bidang_ilmu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getalldosen()
    {
        $this->db->select('*');
        $query = $this->db->get($this->table);
        return $query->result();
    }

}

/* End of file M_dosen.php */
/* Location: ./application/models/M_dosen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-27 17:27:02 */
/* http://harviacode.com */