<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_jam extends CI_Model
{

    public $table = 'tb_jam';
    public $id = 'id_jam';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jam', $q);
	$this->db->or_like('kode_jam', $q);
	$this->db->or_like('nama_jam', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jam', $q);
	$this->db->or_like('kode_jam', $q);
	$this->db->or_like('nama_jam', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getalljam()
    {
        $this->db->select('*');
        $query = $this->db->get($this->table);
        return $query->result();
    }

    function random()
    {
        $sql = "SELECT 
                    a.*
                FROM
                    tb_jam a
                JOIN
                    (SELECT 
                        id_jam
                    FROM
                        tb_jam
                    WHERE
                        RAND() < (SELECT 
                                ((1 / COUNT(*)) * 10)
                            FROM
                                tb_jam)
                ORDER BY RAND()
                LIMIT 6) AS b ON b.id_jam= a.id_jam";
        $data = $this->db->query($sql);
        return $data->result();
    }

}

/* End of file M_jam.php */
/* Location: ./application/models/M_jam.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-01 17:27:05 */
/* http://harviacode.com */