<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_prodi extends CI_Model
{

    public $table = 'tb_prodi';
    public $id = 'id_prodi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_prodi', $q);
	$this->db->or_like('kode_prodiDIKTI', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->or_like('nama_prodi_Eng', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('jenjang', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_prodi', $q);
	$this->db->or_like('kode_prodiDIKTI', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->or_like('nama_prodi_Eng', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('jenjang', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getallprodi()
    {
        $this->db->select('*');
        $query = $this->db->get($this->table);
        return $query->result();
    }

    function join()
    {
        $this->db->select('tb_prodi.id_prodi, tb_prodi.kode_prodiDIKTI, tb_prodi.nama_prodi, tb_prodi.jenjang, tb_prodi.keterangan, tb_prodi.aktif, tb_fakultas.nama_fakultas, tb_fakultas.singkatan');
        $this->db->join('tb_fakultas', 'tb_prodi.id_fakultas = tb_fakultas.id_fakultas');
        $query = $this->db->get($this->table);
        return $query->result();
    }

}

/* End of file M_prodi.php */
/* Location: ./application/models/M_prodi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-30 18:42:35 */
/* http://harviacode.com */