<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_ruangan extends CI_Model
{

    public $table = 'tb_ruangan';
    public $id = 'id_ruang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ruang', $q);
	$this->db->or_like('id_gedung', $q);
	$this->db->or_like('nama_ruang', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ruang', $q);
	$this->db->or_like('id_gedung', $q);
	$this->db->or_like('nama_ruang', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getallruangan()
    {
        $this->db->select('*');
        $query = $this->db->get($this->table);
        return $query->result();
    }

    function join()
    {
        $this->db->select('tb_ruangan.id_ruang, tb_ruangan.nama_ruang, tb_ruangan.kapasitas, tb_ruangan.jenis, tb_ruangan.keterangan, tb_gedung.nama_gedung');
        $this->db->join('tb_gedung', 'tb_ruangan.id_gedung = tb_gedung.id_gedung');
        $this->db->order_by('tb_gedung.nama_gedung', 'asc');
        $query = $this->db->get($this->table);
        return $query->result();
    }

}

/* End of file M_ruangan.php */
/* Location: ./application/models/M_ruangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-27 17:55:43 */
/* http://harviacode.com */