<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_users extends CI_Model
{

    public $table = 'tb_users';
    public $id = 'id_user';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_user', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_user', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getalluser()
    {
        $this->db->select('*');
        $query = $this->db->get($this->table);
        return $query->result();
    }

    function join()
    {
        $this->db->select('tb_users.id_user, tb_users.username, tb_users.password, tb_users.level, tb_users.email, tb_users.no_telp, tb_dosen.nama_dosen, tb_dosen.gelar_depan, tb_dosen.gelar_belakang');
        $this->db->join('tb_dosen', 'tb_users.id_dosen = tb_dosen.id_dosen');
        $query = $this->db->get($this->table);
        return $query->result();
    }

}

/* End of file M_users.php */
/* Location: ./application/models/M_users.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-23 15:34:43 */
/* http://harviacode.com */